receivers:
  otlp:
    protocols:
      http:      

exporters:
  otlphttp:
    compression: gzip
    endpoint: https://us-east-1.aws.edge.axiom.co
    headers:
      authorization: Bearer xaat-7474017e-ddf5-4bd8-a73b-06b576cf22f3
      x-axiom-dataset: macrograph

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp]
    logs:
      receivers: [otlp]
      exporters: [otlphttp]
